#!/bin/bash
  #docker Inspect
COM=$(which docker)
clear
#$CMD ps
echo "Docker Container Inspect"
echo "========================="
echo ""
$COM ps --format 'table {{.ID}}\t{{.Names}}' | tail -n +2 | nl
echo "================"
echo ""
echo "To cancel: n"
echo -n '#:> '
read did

cid=$(docker ps --format '{{.ID}}' | awk "NR==$did")


if [ $did == "n" ]
then
echo "Action cancelled"
fi

if [ $did != "n" ]
then
$COM inspect $cid
fi
