#!/bin/bash
  #docker Inspect
CMD=$("which docker")
clear
$CMD ps
echo "================"
echo ""
echo "To cancel: n"
echo -n 'Docker ID:> '
read did

  if [ $did == "n" ] then
  echo "Action cancelled"
  fi
  
  if [ $did != "n" ] then
  $CMD inspect $did
  fi

