#!/bin/bash
COM=$(which docker)
BSH=$(which bash)
$COM ps -a
WDR=$1

echo -n  'Docker ID #>:'
read input
echo "Killing Container"
$COM kill $input
echo "Removing Container"
#$COM rm $input
$COM ps -a
echo ""
echo -n "Do you want to Clean Docker Containers? [y/n]"
read clean
if [ $clean == "y" ]
then
$BSH $WDR/dclean
echo "Done."
else
return
fi
