#!/bin/bash
COM=$(which docker)
BSH=$(which bash)
WSH=$(which sh)
echo "Docker Container Access"
echo "======================="
echo ""
#$COM ps
$COM ps --format 'table {{.ID}}\t{{.Names}}' | tail -n +2 | nl
echo -n  '#>:'
read input
cid=$(docker ps --format '{{.ID}}' | awk "NR==$input")

echo ""
#echo "[1] /usr/bin/Bash"
#echo "[2] /usr/bin/Sh"
#echo "[3] /bin/Bash"
#echo "[4] /bin/sh"
#echo "[5] /sh"
#echo "[6] /bash"
echo "[1] Your environment SH"
echo "[2] Your environemtn Bash"
echo "[3] Input Environment Path"
echo "[n] Abort"

echo -n 'Which Environment #:>'
read environment

if [ $environment == 1 ]
then
$COM exec -it $cid $BSH
#echo 'hello'
fi

if [ $environment == 2 ]
then
$COM exec -it $cid $WSH
#echo 'hello'
fi

if [ $environment == 3 ]
then
#$COM exec -it $cid $WSH
#echo 'hello'

echo -n "Insert the bash / sh path #:>"
read envpath
$COM exec -it $cid $envpath

fi

if [ $environment == "n" ]
then
echo "Aborted."
fi
