#!/bin/bash
COM=$(which docker)
BSH=$(which bash)
WSH=$(which sh)
echo "View Container Log"
echo "=================="
echo ""
$COM ps --format 'table {{.ID}}\t{{.Names}}' | tail -n +2 | nl
#$COM ps
echo -n  '#>:'
read input
echo ""
cid=$(docker ps --format '{{.ID}}' | awk "NR==$input")
$COM logs $cid
